global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['network:9100']
        labels:
          service: 'node-exporter'
          
  - job_name: 'network-service'
    static_configs:
      - targets: ['network:8080']
        labels:
          service: 'network-api'
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-exporter:9308'] 

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'alert.rules.yml' 