FROM rust:1.76 as builder

WORKDIR /app
COPY . .

RUN cargo build --release

FROM debian:bullseye-slim

WORKDIR /app
COPY --from=builder /app/target/release/snipebot /usr/local/bin/snipebot

EXPOSE 8080

ENV RUST_LOG=info

CMD ["snipebot"]